### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by rpryzant** [Kensuke-Mitsuzawa/JapaneseTokenizers#46]
Seems like this is lacking macOS support?

I installed with
```
pip install JapaneseTokenizer
make install
make install_neologd
```

During `make install`  I received the following error: 
```
install_tokenizers.sh: line 89: ldconfig: command not found
```

And during `make install_neologd` i got:
```
[install-mecab-ipadic-NEologd] :     unxz is not found.
make: *** [install_neologd] Error 1
```

And while trying to run the example starter code, I got
```
[Y/12/06 15:03:43]ERROR - mecab_wrapper.py#__CallMecab:137: ('',)
[Y/12/06 15:03:43]ERROR - mecab_wrapper.py#__CallMecab:138: Possibly Path to userdict is invalid. Check the path
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    mecab_wrapper = JapaneseTokenizer.MecabWrapper(dictType='ipadic')
  File "/Users/rpryzant/kana/venv/lib/python2.7/site-packages/JapaneseTokenizer/mecab_wrapper/mecab_wrapper.py", line 45, in __init__
    self.mecabObj = self.__CallMecab()
  File "/Users/rpryzant/kana/venv/lib/python2.7/site-packages/JapaneseTokenizer/mecab_wrapper/mecab_wrapper.py", line 139, in __CallMecab
    raise subprocess.CalledProcessError(returncode=-1, cmd="Failed to initialize Mecab object")
subprocess.CalledProcessError: Command 'Failed to initialize Mecab object' returned non-zero exit status -1
```

I am running macOS 10.13.1

**Comment by Kensuke-Mitsuzawa** [comment]
@rpryzant thanks for your report and sorry to be late for my reply. I did not run this script in MacOS. But, I think, it does not run on MacOS because MacOS does not have `ldconfig` command. All issues in your issue are rooted from here.

# Resasons

> install_tokenizers.sh: line 89: ldconfig: command not found

This line shows `ldconfig` command does not run on MacOS, and failed to install mecab on your MacOS.

> subprocess.CalledProcessError: Command 'Failed to initialize Mecab object' returned non-zero exit status -1

This line shows that python failed to install the package because mecab is not installed yet on your MacOS.


# Solution

You have to make & install mecab(and other tokenizers if you want) manually.

As I mention [here](https://github.com/Kensuke-Mitsuzawa/JapaneseTokenizers#mecab-1), you can make install mecab manually. please try it.



# By the way

your mac does not have `unxz` command. 

> [install-mecab-ipadic-NEologd] :     unxz is not found.
> make: *** [install_neologd] Error 1

You can install it with `brew`. Try this command.

`$ brew install xz`

**Comment by rpryzant** [comment]
Sorry for my late response as well. Thank you!! Your advice helped me fix my problem.
